#!/usr/bin/env bash

# Author: Gabriel Bellon (fibrasek) <gabriel1490@gmail.com>

music=$(mpc playlist -f "%position% - %artist% - %title%" | sed -e "s/^>/ /" | dmenu -i | cut -d " " -f 1)

if [ "$music" == "" ]; then
    echo "do nothing..."
else
    {
        mpc play "$music"
    } > /dev/null
fi
